### ISSUE TITLE
[Postgres Error] "country" string null - type "string" does not exist

### ISSUE THREAD

**Issue by anouarkacem** [MattieBelt/strapi-plugin-international-fields#20]
### **Bug Report**

When creating a new project, the changing the database to postgres using  `strapi-connector-bookshelf` and add country field, it won't be migrated because of this : `error error: create table "components_supplier_ship_tos" ("id" serial primary key, "country" string null) - type "string" does not exist`

### **Steps to reproduce**

1. Create a new project
2. Change database to postgres
3. Create a content type with country field, in my case it was a repeatble component
4. Launch and boom

### **Code Snippet**

`{
  "collectionName": "components_supplier_ship_tos",
  "info": {
    "name": "ShipTo",
    "icon": "ship"
  },
  "options": {},
  "attributes": {
    "country": {
      "type": "country",
      "columnType": "String" // tried with lower case string and String, same error
    }
  }
}
`

### **System**

- Node v14.15
- NPM v6.14.8
- knex ^0.95.11
- pg ^8.7.1
- strapi 3.6.8
- strapi-connector-bookshelf ^3.6.8

**Comment by anouarkacem** [comment]
I've been diggin' around and noticed that string isn't a postgres type also we can pass a `columnType` as you did, so changed the type to `varchar(255)` and it worked

Not sure if we should consider it as an issue

**Comment by MattieBelt** [comment]
Hey @anouarkacem,

Thanks for noticing this, the `columnType` option indeed should be an correct datatype depending on the db used.
I'll update the README.md to provide the different values that should be used per DB.
